services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: finance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
